version: "3.9"

services:
  automl:
    build:
      context: ./backend/automl
    ports:
      - "5050:5050"
    environment:
      DATASET_PATH: /app/data/dataset
      MODEL_PATH: /app/data/model
    volumes:
      - ./backend/automl/data/dataset:/app/data/dataset
      - ./backend/automl/data/model:/app/data/model
    networks:
      - private-network

networks:
  private-network:
    driver: bridge