name: CI Develope Branch

on:
  pull_request:
    branches:
      - develop
jobs:
  automl-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r backend/automl/requirements.txt
          pip install pytest
      - name: Run unit tests
        run: pytest tests/individuel_tests
      - name: Build AutoML Docker container
        run: docker build -t automl-service ./backend/automl